"""Add paystack reference to Booking

Revision ID: 10b61cae8926
Revises: af4e1997ca1d
Create Date: 2025-05-02 14:23:38.567701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b61cae8926'
down_revision = 'af4e1997ca1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_reference', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_booking_paystack_reference', ['paystack_reference'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('paystack_reference')

    # ### end Alembic commands ###
